### ISSUE TITLE
Unexport `*hook*`?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nhooks#2]
Is it expected to re-export `*hook*` in `nhook`?
Is there a use case?

**Comment by BlueFlo0d** [comment]
I think it might be useful for some introspection? For example, there can be a `log-me` handler, that if you add it to any hook, it will print/record some information every time that hook runs.

**Comment by Ambrevar** [comment]
Fair enough.

While we are at it, isn't this dynamic variable prone to race conditions?  What if multiple threads run the same hook at the same time?

**Comment by BlueFlo0d** [comment]
> Fair enough.
> 
> While we are at it, isn't this dynamic variable prone to race conditions? What if multiple threads run the same hook at the same time?

I'm using dynamic binding to bind `*hook*`, which is thread safe (implemented under the hood by thread local storage).

I looked back at `serapeum`'s use of `*hook*` and it's funny... it seems to confuse lexical and dynamic variable. But whatever.

**Comment by Ambrevar** [comment]
As far as I understand, thread local storage must be made explicit in Bordeeaux threads, using the `:initial-bindings` keyword argument.  Dynamic bindings are not thread-safe otherwise, but I could be wrong.

**Comment by BlueFlo0d** [comment]
> As far as I understand, thread local storage must be made explicit in Bordeeaux threads, using the `:initial-bindings` keyword argument. Dynamic bindings are not thread-safe otherwise, but I could be wrong.

That is for initializing "thread-local global bindings". I'm pretty sure "local bindings" are thread-safe on all major CL implementations. E.g. http://www.sbcl.org/manual/#Special-Variables
