### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nhooks#7]
Seems that we are pretty much ready.  Release 1.0.0 then?  @BlueFlo0d

**Comment by BlueFlo0d** [comment]
Sure, feel free to do it when you're ready -- I'll watch it this time to learn the best practice of releasing on git forge `:)`

**Comment by Ambrevar** [comment]
Done.

The process is simple: update the .asd version and add a Git tag to the commit.
Don't forget to push the tag, since pushing the commit does not automatically push the tag.
